[package]
name = "unnamed"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "unnamed"
path = "src/main.rs"
[profile.release]
debug = true
[dependencies]
unicode-xid = "0.2.2"